### ISSUE TITLE
请问你的Tensorflow的版本是啥？？

### ISSUE THREAD

**Issue by ithjz** [harry19902002/image-style-transfor#1]
[root@localhost code]# /root/anaconda3/bin/python /usr/code/image-style-transfor-master/neural_style.py --content /usr/code/image-style-transfor-master/hjz/1-1a.jpg  --styles  /usr/code/image-style-transfor-master/examples/1-style.jpg --out   /usr/code/image-style-transfor-master/hjz/1-1aout.jpg
WARNING:tensorflow:From /root/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py:175: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Iteration 1/1000
已杀死

**Comment by harry19902002** [comment]
python2 的版本

**Comment by sheldonxzf** [comment]
请问这个怎么解决。
D:\image-style-transfor-master>python neural_style.py --content D:\image-style-transfor-master\1-content --styles D:\image-style-transfor-master\1-style --output D:\image-style-transfor-master\output
Traceback (most recent call last):
  File "neural_style.py", line 152, in <module>
    main()
  File "neural_style.py", line 85, in main
    content_image = imread(options.content)
  File "neural_style.py", line 143, in imread
    return scipy.misc.imread(path).astype(np.float)
  File "C:\Users\aas\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Users\aas\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\misc\pilutil.py", line 164, in imread
    im = Image.open(name)
  File "C:\Users\aas\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\image-style-transfor-master\\1-content'

**Comment by sheldonxzf** [comment]
文件我已经放在那里了。也试过很多的路径或者文件名。
